let questions_answers = {
    "Le PIB est la somme de tout ce qui est produit dans un pays, en valeur" : ["Faux"],
    "L'équation de l'équilibre macro-économique est mesurée grâce aux flux réels" : ["Vrai"],
    "Le PIB signifie Production Internationale Brute" : ["Faux"],
    "Comptablement, le PIB est la somme de toutes les valeurs ajoutées" : ["Vrai"],
    "Le PIB non marchand se mesure au coût des facteurs de l'Etat et des entreprises" : ["Faux"],
    "La FBCF est l'agrégat qui mesure la consommation" : ["Faux"],
    "Le PIB est un indicateur incomplet, il faut le comparer à l'augmentation de la population" : ["Vrai"],
    "Les externalités sont prises en compte dans le PIB" : ["Faux"],
    "Le PIB = somme de tous les revenus" : ["Vrai"],
    "Les entreprises doivent produire à but lucratif" : ["Vrai"],
    "Une externalité est une conséquence induite de l'action d'un agent économique sur un autre agent, sans qu'il l'ait voulu" : ["Vrai"],
    "La perception par les ménages de leur pouvoir d'achat peut différer des calculs de l'INSEE" : ["Vrai"],
    "Un ménage peut n'être composé que d'une personne" : ["Vrai"],
    "L'offre de travail est un flux réel" : ["Vrai"],
    "La fréquentation d'une plateforme numérique entraîne des externalités directes et positives" : ["Vrai"],
    "La financiarisation a poussé les gestionnaires à chercher de la valeur dans tout l'ensemble du processus \"entreprise\"": ["Vrai"],
    "Les externalités créent des phénomènes de dominance" : ["Vrai"],
    "Les entreprises doivent produire à but lucratif": ["Vrai"],
    "Les banques sont encadrées par les autorités publiques" : ["Vrai"],
    "La relation des banques avec ses clients est basée sur la confiance": ["Vrai"],
    "Lorsque la demande est atone, il est conseillé de baisser les taux d'intérêt pour faciliter l'accès à l'investissement" : ["Vrai"],
    "Le problème d'offre est lié à une productivité en berne" : ["Vrai"],
    "Les marchés fonctionnent parfaitement, l'Etat ne doit jamais interférer avec leur fonctionnement ; c'est l'Etat qui dérègle les marchés." : ["Faux"],
    "Quelles propositions sont correctes concernant la fonction de régulation de l'Etat ?" : ["Le marché connaît des défaillances","Il existe des abus de position dominante","Il faut des mesures long terme pour assurer le développement de l'économie"],
    "Lorsque la demande est atone, il est conseillé de baisser les taux d'intérêt pour faciliter l'accès à l'investissement" : ["Vrai"],
    "Un bien non marchand n'a pas de valeur" : ["Faux"],
    "En face d'une \"crise de la demande\", le diagnostic causal fait état de ..." : ["L'accès au crédit est limité par des taux d'intérêt élevés","La consommation des ménages diminue","Les ménages épargnent trop"],
    "Le déficit public contient" : ["Le déficit budgétaire", "Le déficit de la sécurité sociale", "Le déficit des collectivités locales"],
    "Une politique de l'offre c'est encourager la production" : ["Vrai"],
    "Le budget de l'Etat est une prérogative du Président de la République" : ["Faux"],
    "Lorsque l'activité économique ralentit, le budget de l'état" : ["diminue sous le double effet : moins de recettes, plus dépenses","a les recettes qui diminuent (moins d'impôts qui rentrent)","a les dépenses qui augmentent : besoin de davantage de protection sociale"],
    "L'état produit des services non marchands" : ["Vrai"],
    "Le budget de l'Etat influence la croissance économique" : ["Vrai"],
    "Le déficit budgétaire est constitué de :" : ["Du solde négatif entre recettes et dépenses du budget de l'Etat"],
    "Quels sont les instruments de politiques économiques pouvant être utilisés directement par l'Etat français en 2017" : [ "Les recettes du budget", "Les dépenses du budget","Les mesures législatives"],
    "Constituent une politique de l'offre" : [ "Alléger les impôts des entreprises", "encourager l'innovation", "améliorer la compétitivité des entreprises", "Mieux former la population"],
    "A quel poste du budget appartient l'opération mentionnée ?" : ["Pensions de retraites → Dépenses d'intervention","Salaires des fonctionnaires → Dépenses de fonctionnement","Allocations chômage → Dépenses d'intervention","Collecte de la TVA → Recettes fiscales","Construction d'infrastructures autoroutières → Dépenses d'investissement","Bourses aux étudiants → Dépenses d'intervention","Taxe d'apprentissage → Recettes fiscales","Impôt sur les bénéfices des entreprises → Recettes fiscales","Construction de logements étudiants → Dépenses d'investissement","Taxe sur les loyers → Recettes fiscales"],
    "Constituent une politique de la demande" : ["baisser les impôts des ménages", "augmenter les salaires", "Distribuer des revenus", "Mieux former la population", "Faciliter l'accès au crédit"],
    "(années 2015 à 2020) - Ordre de grandeur du PIB français/habitant en euros" : ["34 000"],
    "Les revenus secondaires sont les revenus après redistribution de l'état" : ["Vrai"],
    "Sont des composantes de l'offre" : ["La production", "Les importations"],
    "La mesure de l'augmentation de la qualité des produits est difficile à mesurer par l'INSEE" : ["Vrai"],
    "Le PIB est la quantité de richesse qui apparaît dans un pays sur une année" : ["Vrai"],
    "le PIB mesure la production nationale" : ["Vrai"],
    "Un agrégat est la mesure d'une grandeur économique" : ["Vrai"],
    "Les revenus dépendent des prix" : ["Faux"],
    "Le solde de la balance commerciale mesure les échanges commerciaux avec l'extérieur" : ["Vrai"],
    "Revenus = salaires" : ["Faux"],
    "La balance commerciale peut se résumer en solde = X - M" : ["Vrai"],
    "L'INSEE signifie Institut National de la Société Economique et de l'Etat" : ["Faux"],
    "L'économie nationale ne peut être appréhendée sans importation et exportation" : ["Vrai"],
    "Si on fait abstraction du temps, l'épargne est l'investissement"  : ["Vrai"],
    "Le PIB capture la performance économique d’un pays en un chiffre" : ["Vrai"],
    "Que signifie cette lettre dans l'équation de l'équilibre macro économique ?" :["C → Consommation", "X → Exportations", "I → Investissement", "G → Rôle de l'Etat","P → Production","M → Importations"],
    "Le PIB est la mesure du patrimoine d'un pays" : ["Faux"],
    "Le PIB marchand se calcule à partir de la Valeur ajoutée des entreprises" : ["Vrai"],
    "(années 2015 à 2020) - Ordre de grandeur du PIB français en euros" : ["2 200 milliards"],
    "Le PIB est la somme de tous les revenus" : ["Vrai"],
    "Le Revenu national (flux monétaire) est égal à la production" : ["Vrai"],
    "Le revenu national se compose de .." : ["de revenus du travail", "de revenus du capital", "de revenus mixtes"],
    "les revenus secondaires sont utilisés dans la consommation ou dans l'épargne" : ["Vrai"],
    "Les ménages arbitrent l'utilisation de leur revenu entre consommation et épargne" : ["Vrai"],
    "Quelles sont les limites de l'indicateur PIB pour décrire la santé de l'économie" : ["Epuisement des ressources minières, fossiles","Pollution de ressources","L'économie domestique","L'économie souterraine n'est pas prise en compte", "Ne tient pas compte de la qualité intrinsèque des produits", "La distorsion marchand/non-marchand", "doit être calculé à prix constant"],
    "Pour un pays et une période donnée...\nSomme des dépenses de consommation = somme des revenus = somme des produits" : ["Vrai"],
    "Pour comparer le PIB d’une année sur l’autre il faut comparer les productions valorisées à prix constants" : ["Vrai"],
    "La mesure de la richesse nationale se base sur la notion de biens et services réels et non la monnaie" : ["Vrai"],
    "Sont des composantes de la demande" : ["La consommation","L'investissement","Les exportations","Le rôle de l'Etat"],
    "Quelles sont les propositions exactes à propos du PIB ?" : ["Le PIB est une mesure de la production","Le PIB en volume s'exprime en unité monétaire (milliards d'euros pour la France)", "La base de calcul du PIB est la somme des valeurs ajoutées", "Le PIB va permettre de calculer la croissance (ou récession) d'un pays"],
    "Les services de la fonction publique sont comptés dans le PIB pour leur coût et non leur prix" : ["Vrai"],
    "Le taux de prélèvement obligatoire avec les cotisations sociales, pour la France en 2019 s'établit autour de 60% du PIB" : ["Vrai"],
    "Associez le montant (ordre de grandeur) à la grandeur économique qu'il mesure pour 2019 en France" : ["-3% → Décifict public/PIB", "98% → Dette public/PIB", "8% → Taux de chômage","67 millions d'individus → habitants", "35 000 euros → PIB/habitant", "2 430 milliards d'euros → PIB"],
    "Le PIB s'exprime en %" : ["Faux"],
    "Le PIB est un bon indicateur du niveau de vie" : ["Faux"],
    "Le PIB ne prend pas en compte ..." : ["Le bénévolat", "La production domestique (jardinage)", "Les externalités négatives sur l'environnement", "La diminution des ressource en matières premières"],
    "Observez le graphique représentant la croissance française en valeur (bleue) et en volume (jaune).\nPour quelle(s) raison(s), des points dans les années 1970 à 1980 (environ) sont-ils inversés (ne vont pas dans le même sens) ?" : ["Le PIB augmente en valeur mais diminue en volume", "L'inflation est très importante", "La hausse des prix masque la faiblesse des quantités produites"],
    "IDH signifie : Indicateur D'Humanité" : ["Faux"],
    "Un agent économique est identifié par sa fonction dans l'économie" : ["Vrai"],
    "Il n'est pas nécessaire de \"trop\" réguler les phénomène de dominance des plateformes à cause de la volatilité des utilisateurs" : ["Vrai"],
    "Le rôle régalien de l'état est de produire" : ["Faux"],
    "L'économie distingue les flux de biens réels des flux monétaires" : ["Vrai"],
    "Les dépenses de consommations correspondent à un flux réel" : ["Faux"],
    "Quelle est la fonction économique des ménages" : ["La consommation"],
    "Les 3 grandes fonctions de l'activité économique sont…" : ["Production, répartition, consommation"],
    "L'état joue un rôle complexe dans l'économie" : ["Vrai"],
    "Le versement du salaire est un flux monétaire" : ["Vrai"],
    "Le financiarisation des entreprises est la conséquence de revenus différés dans le temps" : ["Vrai"],
    "Le pouvoir d'achat correspond à ce que les ménages peuvent consommer avec leur revenu" : ["Vrai"],
    "Une entreprise c'est" : ["une cellule sociale", "une unité de création de richesse", "Un ensemble de partie prenante", "Des salariés", "Un système social organisé ouvert", "Des dirigeants et des manager", "Des clients"],
    "La mesure de la richesse nationale se base sur la notion de biens et services réels et non la monnaie" : ["Vrai"],
    "La macroéconomie s'intéresse au comportement des agents économiques" : ["Faux"],
    "Le circuit économique révèle plusieurs types de marché…" : ["Le marché du travail","Le marché des biens et services","Le marché des capitaux (financement)"],
    "Le lieu commun \"faire payer les entreprises\" revient à faire payer les partie prenantes" : ["Vrai"],
    "L'achat d'équipement pour la maison est un flux monétaire" : ["Faux"],
    "Le versement des intérêts correspond à un flux réel" : ["Faux"],
    "Quelle est la fonction économique de l'état ? (1 réponse)" : ["La redistribution"],
    "La fonction économique des entreprises est la consommation intermédiaire" : ["Faux"],
    "La pollution est une externalité négative" : ["Vrai"],
    "La macroéconomie s'intéresse aux fonctions économiques" : ["Vrai"],
    "Quelle est la fonction économique des entreprises" : ["La production"],
    "A l'origine, aux USA, les fonds de pension placent l'épargne de leurs clients dans les entreprises":["Vrai"],
    "Les mots clés de la théorie keynesienne sont" : ["Intervention de l'Etat","Stimulation de la demande"],
    "Les mots clés de la théorie marxiste sont" : ["Bourgeoisie", "Prolétaire", "Travail", "Révolution"],
    "Les mots clés de la théorie économique classique sont" : ["Libéralisme", "Marché", "Main invisible", "Avantage comparatif", "Avantage absolu"],
    "Associer le concept au courant économique" : ["L'épargne stérile doit être réinjectée dans l'économie et servir à investir → Théorie keynesienne", "Les dysfonctionnements du marché sont dus à l'asymétrie de l'information → Théorie monétariste", "La crise s'analyse comme un problème de débouchés → Théorie keynesienne","Il faut lutter contre l'inflation en augmentant les taux d'intérêt → Théorie monétariste","La monnaie n'est pas neutre : il faut baisser les taux d'intérêt → Théorie keynesienne","La monnaie n'est qu'un voile → Théorie libérale classique","Le prix est fixé en fonction de l'utilité marginale → Théorie néo-libérale","La propriété c'est le vol → Théorie Marxiste","L'investissement dans le capital productif a comme conséquence une diminution des salaires → Théorie Marxiste","La crise est due à une surproduction → Théorie Marxiste","Les acteurs économiques confrontent leurs intérêts et se comportent de manière rationnelle → Théorie néo-libérale","L'augmentation de la masse monétaire doit être calquée sur la croissance → Théorie monétariste","L'exploitation des travailleurs → Théorie Marxiste","La liberté des échanges est une des garanties du bon fonctionnement de l'économie → Théorie libérale classique","L'intervention de l'Etat → Théorie keynesienne","La spécialisation du travail → Théorie libérale classique","La division du travail → Théorie libérale classique"],
    "L'offre est la quantité que les producteurs ont l'intention de proposer au marché en fonction des prix possibles" : ["Vrai"],
    "La pénurie est un excès d'offre sur la demande" : ["Faux"],
    "La date de l\"économie moderne c’est l’an 2000" : ["Faux"],
    "« Comprendre l’économie est indispensable pour comprendre la marche du monde » est une affirmation de Vincent Bernard" : ["Vrai"],
    "L’économie est une science sociale et humaine" : ["Vrai"],
    "L’opinion publique admet l’existence de 4 révolutions industrielles" : ["Vrai"],
    "L’économie porte sur l’étude des ressources à disposition des êtres humains" : ["Faux"],
    "L’économie n’est mondiale que depuis 1800" : ["Faux"],
    "Le droit de propriété est à la base du raisonnement économique" : ["Vrai"],
    "L’économétrie est une branche de l’économie" : ["Vrai"],
    "L’eau de mer est une ressource rare" : ["Faux"],
    "L’économie distingue plusieurs types de besoins" : ["Vrai"],
    "L’eau est une ressource rare au sens économique" : ["Faux"],
    "Le pain est une ressource rare" : ["Vrai"],
    "L’économie s’occupe aussi des services" : ["Vrai"],
    "La notion de richesse est similaire à celle de production pour l’économiste" : ["Vrai"],
    "Le moyen de satisfaire les besoins est la production" : ["Vrai"],
    "Un bijou avec un diamant est une ressource rare" : ["Vrai"],
    "Le problème économique vient de la rareté des biens de consommation" : ["Faux"],
    "La définition économique d’une ressource rare c’est « nécessite un effort »" : ["Vrai"],
    "Les ressources rares sont des ressources peu présentes sur terre" : ["Faux"],
    "Les ressources rares peuvent se résumer en capital (au sens productif) et travail" : ["Vrai"],
    "Une voiture électrique est une ressource rare" : ["Vrai"],
    "L’économie ne s’occupe que des biens de consommation" : ["Faux"],
    "L’économie étudie la satisfaction des besoins" : ["Faux"],
    "Les activités principales ou opérationnelles contribuent directement au processus de production ou commercialisation" : ["Vrai"],
    "Les activités support ne peuvent pas être créatrices de valeur, elles sont imposées par l'administration de l'entreprise" : ["Faux"],
    "L'avantage concurrentiel permet à l'entreprise d'accaparer davantage de valeur sur son marché" : ["Vrai"],
    "La fragmentation des chaînes de valeur signifie que les opérations nécessaires à l'élaboration d'un produit sont éclatées dans un grand nombre de pays" : ["Vrai"],
    "Un coût est un ensemble de prix" : ["Vrai"],
    "Un prix est une valeur fixée par le marché" : ["Vrai"],
    "La notion de valeur en économie est l'importance accordée à un bien ou service" : ["Vrai"],
    "La mesure du commerce en valeur ajoutée peut donner une idée plus juste de la réelle richesse produite au niveau mondial" : ["Vrai"],
    "La notion de valeur en économie est l'importance accordée à un bien ou service" : ["Vrai"],
    "La valeur ajoutée résulte de la soustraction des consommations intermédiaires à la production" : ["Vrai"],
    "Face à une chaîne de valeur fragmentée, une nouvelle source de valeur tient à la coordination des différents acteurs" : ["Vrai"],
    "Les marginalistes ont théorisé l'utilité pour expliquer la valeur des biens" : ["Vrai"],
    "La fragmentation des chaînes de valeur conduit à enregistrer \"comptablement\" plusieurs fois les mêmes opérations pour un même produit" : ["Vrai"],
    "Dans le cas d'une fragmentation de la production, la valeur totale d'un produit est la somme des valeurs ajoutées se rapportant à ce produit dans chaque pays contribuant à son élaboration" : ["Vrai"],
    "Coût et prix, c'est la même chose" : ["Faux"],
    "Les chiffres du commerce extérieur de chaque nation enregistrent d'une part les importations et d'autre part les exportations" : ["Vrai"],
    "L'utilité est l'aptitude d'un bien ou service à satisfaire un besoin" : ["Vrai"],
    "La valeur ajoutée est d'autant plus grande que le coût des facteurs de production est faible" : ["Faux"],
    "La fragmentation des chaînes de valeur conduit à gongler artificiellement le montant des échanges internationaux" : ["Vrai"],
    "Lorque la demande d'un bien ne varie pas et que l'offre augmente, alors le prix augmente" : ["Faux"],
    "La variation du prix sur un marché est fonction de l'offre ou de la demande (pas les 2)" : ["Faux"],
    "L'atomicité du marché signifie qu'il existe un nombre important d'offreurs" : ["Vrai"],
    "La demande est la quantité que les producteurs ont l'intention de proposer au marché en fonction des prix possibles" : ["Faux"],
    "Le monopole rend captifs les demandeurs" : ["Vrai"],
    "La concurrence est la compétition entre entreprises pour proposer leurs produits aux demandeurs" : ["Vrai"],
    "La concurrence parfaite implique des conditions parfaitement identiques pour tous sur le marché" : ["Vrai"],
    "Plus le prix est bas, plus il y a de demandeurs" : ["Vrai"],
    "Les entreprises est l'agent économique dont l'intérêt à agir est le profit" : ["Vrai"],
    "La loi de l'offre et de la demande explique que la quantité de biens ou services disponibles sur un marché \"libre\" s'ajuste automatiquement à la quantité souhaitée en fonction du prix" : ["Vrai"],
    "Les producteurs déterminent l'offre" : ["Vrai"],
    "Un oligopsone est un marché qui présente une multitude d'offreurs et quelques demandeurs" : ["Vrai"],
    "L'économie d'échelle c'est quand le coût unitaire du produit diminue lorsqu'on produit beaucoup" : ["Vrai"],
    "La propriété intellectuelle est une restriction à la libre concurrence" : ["Vrai"],
    "Il existe plusieurs \"marchés\"" : ["Vrai"],
    "Les acheteurs constituent la demande" : ["Vrai"],
    "La surproduction est un excès d'offre sur la demande" : ["Vrai"],
    "L'intérêt des demandeurs est le profit" : ["Faux"],
    "L'augmentation du coût de production peut être compensée par des gains de productivité" : ["Vrai"],
    "La loi de l'offre et de la demande explique la formation des prix" : ["Vrai"],
    "Une institution est un ensemble de règles" : ["Vrai"],
    "Les vendeurs constituent la demande" : ["Faux"],
    "L'atomicité du marché signifie qu'il existe un nombre important d'offreurs" : ["Vrai"],
    "Un oligopole présente le risque d'une entente sur les prix" : ["Vrai"],
    "L'offre est la quantité que les producteurs ont l'intention de proposer au marché en fonction des prix possibles" : ["Vrai"],
    "Tout agent économique n'agit que s'il y trouve un intérêt est un postulat de base" : ["Vrai"],
    "Le corps humain est un bien marchand" : ["Faux"],
    "La demande peut être stimulée par le marketing" : ["Vrai"],
    "Lorsque les revenus d'un pays diminuent, l'offre va elle aussi diminuer" : ["Vrai"],
    "Plus le coût de production est élevé, plus l'offre est élevée" : ["Faux"],
    "Il existe un marché lorsque les biens sont considérés comme des marchandises" : ["Vrai"],
    "Un système économique se définit comme étant les \"règles du jeu\" de l'économie (production, répartition et échange)" : ["Vrai"],
    "En théorie, pour qu'il y ait marché, il faut que les rapports entre offre et demande soient libres" : ["Vrai"],
    "Sur un marché, agissent des vendeurs et des acheteurs" : ["Vrai"],
    "La paradoxe : \"la diminution du nombre de producteurs peut faire baisser les prix\" est possible" : ["Vrai"],
    "L'approche de la loi de l'offre et de la demande est théorique" : ["Vrai"],
    "En France, le sang n'est pas un bien marchand" : ["Vrai"],
    "La pénurie est un excès d'offre sur la demande" : ["Faux"],
    "Selon les monétaristes, l'Etat doit intervenir pour réduire la distribution de revenus" : ["Faux"],
    "Le courant des monétaristes voit le jour dans un contexte inflationniste" : ["Vrai"],
    "C'est en soutenant l'investissement que l'Etat peut faire bénéficier l'économie du multiplicateur keynesien" : ["Vrai"],
    "L'avantage comparatif consiste à se spécialiser là où l'on \"perd\" le moins" : ["Vrai"],
    "Selon Keynes, l'Etat doit soutenir impérativement la consommation avant toute chose" : ["Faux"],
    "Marx détermine la cause des crises à partir de la surproduction" : ["Vrai"],
    "L'avantage absolu consiste à se spécialiser là où on possède la meilleure compétence" : ["Vrai"],
    "Le coût d’opportunité d’une action ou d’un choix économique est la mesure de la valeur des actions ou choix auxquels on renonce" : ["Vrai"],
    "Les néo-classiques élaborent une théorie de la valeur subjective" : ["Vrai"],
    "Les \"classiques\" n'ont pas de considération spécifique pour la monnaie : c'est juste une unité de compte" : ["Vrai"],
    "Le libéralisme provient de nos égoismes individuels" : ["Vrai"],
    "La division du travail est indissociable de la liberté des échanges, sinon, ça ne marche pas" : ["Vrai"],
    "Les physiocrates entérinent le fait que la richesse ne peut venir que de la terre" : ["Vrai"],
    "Les théories classique et marxiste ont comme point commun que la seule valeur économique qui vaille provient du travail" : ["Vrai"],
    "La France a pu dévaluer sa monnaie en 2020 (COVID)" : ["Faux"],
    "Keynes prône une intervention de l'Etat dans l'économie pour résoudre les crises" : ["Vrai"],
    "La main invisible peut être définie comme la somme de nos intérêts individuels" : ["Vrai"],
    "La compétence incite à la division du travail ; cette spécialisation accroit les compétences" : ["Vrai"],
    "C'est l'étude du comportement du consommateur et de la masse monétaire qui est à la base des théories de Friedman" : ["Vrai"],
    "Que comprend le coût de production ?" : ["Le prix des matières premières","Les salaires","L'amortissement des machines","La note d'EDF"],
    "Pour qu'il y ait ECONOMIE de marché, quelles conditions doivent être remplies ?" : ["Le droit à la propriété (marché de la terre)", "Un marché de la monnaie et/ou du financement", "Un marché du travail", "Un ou plusieurs marchés de biens et services"],
    "Quels arguments développe Kaplan pour expliquer la valeur des choses ?" : ["La subjectivité de nos perceptions","Le bénéfice mutuel de l'échange"],
    "Comment les entreprises peuvent elles améliorer les maillons de leur chaîne de valeur ?" : ["Augmenter la qualification des salariés","Sous-traiter certaines de leurs activités","Développer des relations de coopération avec leurs fournisseurs"],
    "A quelle grande catégorie de la chaîne de valeur appartient ce maillon ?\nD'après Porter" : ["Système d'information → Fonctionnel ou support","logistique amont → Opérationnel ou principal", "Gestion financière → Fonctionnel ou support","Gestion des ressources humaines → Fonctionnel ou support","approvisionnement → Opérationnel ou principal","vente → Opérationnel ou principal"],
    "L'économie s'intéresse à (au-x)..." : ["La production","La distribution", "La consommation", "Les échanges"],
    "Pourquoi nos besoins sont-ils illimités ?\nCar..." : ["La pauvreté existe très largement sur la planète", "La publicité nous incite à toujours consommer davantage", "Il y a un décalage dans le temps entre le désir et la satisfaction du besoin"],
    "Le problème économique est que..." : ["les ressources sont rares face à des besoins humains illimités"],
    "Les facteurs de production sont" : ["Matières premières", "Energie", "Travail", "Capital technique (machines)", "financement"],
    "A quoi sert la valeur ajoutée ?" : ["A rémunérer les facteurs de production"],
    "Comment l'entreprise peut-elle capter davantage de valeur sur son marché ?" : ["Produire moins cher que ses concurrents", "Produire mieux pour faire accepter un prix supérieur"],
    "D'après le schéma de la \"chaîne de valeur\" de Mickael Porter, quelles sont les 2 grandes catégories d'activité dans l'entreprise ?\n... les activités" : ["principales", "opérationnelles", "support", "fonctionnelles"],
    "La concurrence parfaite implique que le prix du marché s'établit toujours au plus bas" : ["Vrai"],
    "Quels sont les déterminants de la demande ?" : ["Les revenus", "Les désirs des acheteurs", "Le nombre d'acheteurs"],
}
